const Categories = [
    { id: "0", value: "All Categories" ,imgName:"art.jpg"  },
    { id: "1", value: "Antiques" , imgName:"antique.jpg" },
    { id: "2", value: "Art", imgName:"art.jpg" },
    { id: "3", value: "Baby", imgName:"baby.jpg"  },
    { id: "4", value: "Books" , imgName:"book.jpg" },
    { id: "5", value: "Cameras" , imgName:"camera.jpeg" },
    { id: "6", value: "Cell Phones & Accessories" , imgName:"cellphone.jpeg" },
    { id: "7", value: "Clothing, Shoes & Accessories", imgName:"clothings.jpg"  },
    { id: "8", value: "Computers & Accessories" , imgName:"it.jpg"},
    { id: "9", value: "Consumer Electronics", imgName:"consumer.jpeg"  },
    { id: "10", value: "DVDs & Movies" , imgName:"movie.jpg" },
    { id: "11", value: "Home & Garden" , imgName:"home.jpg" },
    { id: "12", value: "Jewelry & Watches" , imgName:"jewellery.jpg" },
    { id: "13", value: "Musical Instruments & Gear" , imgName:"music.jpg" },
    { id: "14", value: "Pet Supplies" , imgName:"pet.jpeg" },
    { id: "15", value: "Sports", imgName:"sport.jpg"  },
    { id: "16", value: "Toys & Hobbies", imgName:"toys.jpeg"  },
    { id: "17", value: "Video Games & Consoles", imgName:"game.jpg"  },
    { id: "18", value: "Others", imgName:"art.jpg"  }]
export default Categories;