const Categories = [
    { id: "0", value: "All Categories" },
    { id: "1", value: "Antiques" },
    { id: "2", value: "Art" },
    { id: "3", value: "Baby" },
    { id: "4", value: "Books" },
    { id: "5", value: "Cameras" },
    { id: "6", value: "Cell Phones & Accessories" },
    { id: "7", value: "Clothing, Shoes & Accessories" },
    { id: "8", value: "Computers & Accessories" },
    { id: "9", value: "Consumer Electronics" },
    { id: "10", value: "DVDs & Movies" },
    { id: "11", value: "Home & Garden" },
    { id: "12", value: "Jewelry & Watches" },
    { id: "13", value: "Musical Instruments & Gear" },
    { id: "14", value: "Pet Supplies" },
    { id: "15", value: "Sports" },
    { id: "16", value: "Toys & Hobbies" },
    { id: "17", value: "Video Games & Consoles" },
    { id: "18", value: "Others" }]
export default Categories;